# service config
service:
  chain_id: irishub
  node_rpc_addr: http://localhost:26657
  node_grpc_addr: localhost:9090
  key_path: .keys
  key_name: sp
  fee: 3stake
  key_algorithm: secp256k1

API:
  random-seed-api: https://www.random.org/cgi-bin/randbyte?nbytes=32&format=h

monitor:
  interval: 5
  prometheus_addr: 0.0.0.0:8888
  base_denom: stake
  provider_addr:
    - iaa1hs7s54kc60pcrpssm8xhfvdqj6cmg0kevr8r9s

balance:
  threshold: 10
