# service config
service:
  chain_id: irishub
  node_rpc_addr: http://localhost:26657
  node_grpc_addr: localhost:9090
  key_path: .keys
  key_name: node0
  fee: 1iris
  key_algorithm: secp256k1

API:
  random-seed-api: https://www.random.org/cgi-bin/randbyte?nbytes=32&format=h

monitor:
  interval: 5
  prometheus_addr: 0.0.0.0:8888
  base_denom: uiris
  provider_addr:
    - iaa1vczh0qgek4nskcr3vng3akmz4qjaf3ah6wp24k

balance:
  threshold: 10
